FROM microsoft/dotnet:2.2-sdk AS build
RUN mkdir /src
WORKDIR /src
COPY . ./
RUN ls -l
RUN dotnet publish ./a-console-app.csproj -o /tmp/app/  -c Release
 
FROM microsoft/dotnet:2.2-runtime AS base
RUN mkdir /app
WORKDIR /app
COPY --from=build /tmp/app .

 ENTRYPOINT ["dotnet", "a-console-app.dll"]
 
 