FROM microsoft/dotnet:2.1-sdk-alpine AS build
RUN mkdir /src
WORKDIR /src
COPY . ./

RUN dotnet publish ./a-console-app.csproj -o /tmp/app/  -c Release


FROM microsoft/dotnet:2.1-runtime-alpine AS base
RUN mkdir /app
WORKDIR /app
COPY --from=build /tmp/app .

 ENTRYPOINT ["dotnet", "a-console-app.dll"]
 
 